### ISSUE TITLE
すさレビュー

### ISSUE THREAD

**Issue by susatthi** [nozomi-koborinai/flutter-reference-app#1]
```
お時間のある時に、ソースコードレビューをお願いします。
アーキテクチャの観点からご指摘を頂けると嬉しいです。
ソースの書き方についてもアドバイス頂けたら嬉しいです。
また、アプリケーション層にはどのような役割を持たせたらいいのでしょうか？
```

僭越ながらご指名頂きましたのでレビューさせて頂きました！
指摘をすべて洗い出しているわけではありませんが、主にアーキテクチャに関する点についてレビュー致しました！

# 全体の感想

- README に画像を載せてるのがよいと思いました！
- Riverpod の使い方を悩んでいるのかな、と感じました！Riverpod の依存性注入（DI） を使うと、テストが容易になったり、コンストラクタでバケツリレーが不要になりますので、是非 Riverpod の使い方をマスターしてほしいです！
- アプリケーション層は自分もまだその必要性を感じていないのでコメントできないです！すみません。。。

# レビュー

## Riverpod の DI 機能を使って各層の依存関係を整理しましょう

https://github.com/nzmgfdprs/repository_riverpod_mvvm/blob/0df7b5e9847c80853a20084cdb101c6a33a91e6d/lib/data_layer/post_repository.dart#L9

`PostRepository` は `FirebaseFirestore.instance` に依存しているので、`FirebaseFirestore.instance` を Riverpod の DI で外部から注入してあげましょう。`PostRepository`のテストコードを書いてみると、そのメリットを実感できると思います。

以下のようにすると、`firebaseFirestoreProvider`の中身をモックに差し替えることでテストが可能になります。
また、外から `PostRepository` を使えるようにするために、`firebasePostRepositoryProvider` も用意しておきます。

```dart
final firebaseFirestoreProvider = Provider(
  (_) => FirebaseFirestore.instance,
);

// PostRepository（実体） ではなく IPostRepository （インターフェース）を返してあげる
final firebasePostRepositoryProvider = Provider<IPostRepository>(
  (ref) => PostRepository(
    // FirebaseFirestoreインスタンスを注入する
    store: ref.watch(firebaseFirestoreProvider),
  ),
);

class PostRepository implements IPostRepository {
  PostRepository({
    required this.store,
  });

  final FirebaseFirestore store;

  ///postsコレクション
  @override
  get postsCol async => store.collection('posts');
```

プレゼンテーション層が `IPostRepository` を使うときは、`ref.watch(firebasePostRepositoryProvider)` とすることで `IPostRepository`  を取得できます。しかし、これでは、プレゼンテーション層がデータ層に依存してしまいます。プレゼンテーション層はドメイン層とアプリケーション層のみに依存するべきです。この問題は Riverpod の overrides を使って以下のように回避できます。

まず、ドメイン層のリポジトリに次のように空の `IPostRepository` を返すプロバイダーを定義します。

```dart
final postRepositoryProvider = Provider<IPostRepository>(
  (_) => throw UnimplementedError(),
);
```

そして、`main()` で、次のように上書きしてあげます。

```dart
void main() async {
  runApp(
    ProviderScope(
      overrides: [
        postRepositoryProvider
            .overrideWithProvider(firebasePostRepositoryProvider),
      ],
      child: const MyApp(),
    ),
  );
}
```

こうすることで、プレゼンテーション層が `IPostRepository` を使うときは、ドメイン層の `postRepositoryProvider` を使って `IPostRepository`  を取得できるようになり、データ層への依存が無くなります。

https://github.com/nzmgfdprs/repository_riverpod_mvvm/blob/0df7b5e9847c80853a20084cdb101c6a33a91e6d/lib/presentation_layer/view_models/post_page_view_model.dart#L21

`PostPageViewModel` は `IPostRepository` に依存しているので、コンストラクタで外部から受け取るこのコードは良いと思います！外から `PostPageViewModel` を使えるようにするために、`postPageViewModelProvider` を用意してあげましょう。その際、`postRepositoryProvider` を使って `IPostRepository` を取得して注入してあげます。

```
final postPageViewModelProvider = Provider(
  (ref) => PostPageViewModel(
    ref.watch(postRepositoryProvider),
  ),
);
```

https://github.com/nzmgfdprs/repository_riverpod_mvvm/blob/0df7b5e9847c80853a20084cdb101c6a33a91e6d/lib/presentation_layer/views/post_page.dart#L6-L28

`PostPage` 内で `PostPageViewModel ` を使いたいときは、次のようにダイレクトに取得できるようになります。かなりすっきり書けますね！ViewModelをメンバ変数に保持する必要も無いので Stateless の `ConsumerWidget` でいけます。

```dart
class PostPage extends ConsumerWidget {
  const PostPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final vm = ref.watch(postPageViewModelProvider);
    return Scaffold(
```

https://github.com/nzmgfdprs/repository_riverpod_mvvm/blob/0df7b5e9847c80853a20084cdb101c6a33a91e6d/lib/presentation_layer/view_models/time_line_page_view_model.dart#L42-L48

 `PostPage` はコンストラクタに何も受け取らないので、以下のように簡素に書けます。

```dart
  Future<void> onPost(BuildContext context) async {
    Navigator.push(
      context,
      MaterialPageRoute(
        builder: (context) => const PostPage(),
      ),
    );
  }
```

## データ層のモデルとドメイン層のモデルを分けた方が良いと思います

https://github.com/nzmgfdprs/repository_riverpod_mvvm/blob/0df7b5e9847c80853a20084cdb101c6a33a91e6d/lib/domain_layer/models/post.dart#L8-L15

`JsonKey`があることから、データ層のリポジトリでFirestoreから受け取ったJSONデータを直接ドメイン層のエンティティ（このGitHubリポジトリ上ではモデルと呼ばれている）に変換する意図を感じます。ドメイン層で定義するエンティティは、どの層にも依存しないのがよいので（データ層都合で変更がおきたときに、ドメイン層まで変更が影響してしまう）、直接変換するのではなく、一度データ層用のモデルを挟むのがよいと思います。今回のアプリは小さいのでこれで問題なく動くと思いますが。。

こんなイメージです。
データ層のリポジトリで、Firestoreから受け取ったデータ（Map）を、データ層用のクラス（PostDocument）にfreezedのfromJsonを使って変換する。次に、PostDocumentをドメイン層のエンティティであるPostクラスに変換する。データ層のリポジトリはPostクラスを返す。

https://github.com/susatthi/github-search/blob/32c121e05a1681a9885b5b292db208559d746847/lib/infrastructure/github/repo/repo_repository.dart#L59-L66

同じ事を私は上記でやってます。data（Map）をjsonObject（データ層用のクラス）に変換し、jsonObjectをSearchReposResult（ドメイン層のエンティティ）に変換して返しています。

# おすすめのパッケージ

- 厳しめの lint にすることをおすすめします！ https://pub.dev/packages/pedantic_mono

**Comment by susatthi** [comment]
https://github.com/nzmgfdprs/repository_riverpod_mvvm/tree/f92c441fc773cc539ab61dae554f67c64dfb2a84
を追加レビューしました！

# 全体の感想

- 半分くらいは改善されたと思います！頑張ってください！

# レビュー

## レイヤーを意識しましょう

https://github.com/nzmgfdprs/repository_riverpod_mvvm/blob/f92c441fc773cc539ab61dae554f67c64dfb2a84/lib/domain_layer/providers.dart#L4-L5

ドメイン層は、どの層にも依存してはいけないので、ここにインフラストラクチャ層のファイルの import があってはいけないです〜。インフラストラクチャ層に移動しましょう！

## リポジトリ（実体）が受け取るコンストラクタ

https://github.com/nzmgfdprs/repository_riverpod_mvvm/blob/f92c441fc773cc539ab61dae554f67c64dfb2a84/lib/data_layer/repositories/post_repository.dart#L6-L17

自分も最近気づいたのですが、Firestore関連のリポジトリ（実体）がコンストラクタで受け取る情報として、`FirebaseFirestore` ではなく、`CollectionReference` を受け取るようにすると、依存関係が明確になるし、リポジトリ（実体）の中の実装がスッキリします！

自分は、最近、こんな実装にしました！

```dart
final firebaseFirestoreProvider = Provider(
  (_) => FirebaseFirestore.instance,
);

final postsCollectionNameProvider = Provider(
  (_) => 'posts',
);

final postsCollectionRefProvider =
    Provider<CollectionReference<Map<String, dynamic>>>(
  (ref) => ref
      .watch(firebaseFirestoreProvider)
      .collection(ref.watch(postsCollectionNameProvider)),
);

final firebasePostRepositoryProvider = Provider<IPostRepository>(
  (ref) => PostRepository(
    collectionRef: ref.watch(postsCollectionRefProvider),
  ),
);

class PostRepository implements IPostRepository {
  PostRepository({
    required this.collectionRef,
  });

  final CollectionReference<Map<String, dynamic>> collectionRef;

  ///投稿新規追加
  @override
  Future<void> addPost(Post newPost) async => await collectionRef
      .add({'content': newPost.content, 'account_id': newPost.accountId});
```

## ViewModelの生成にもRiverpodが使えます

https://github.com/nzmgfdprs/repository_riverpod_mvvm/blob/f92c441fc773cc539ab61dae554f67c64dfb2a84/lib/presentation_layer/views/post_page.dart#L13

と

https://github.com/nzmgfdprs/repository_riverpod_mvvm/blob/f92c441fc773cc539ab61dae554f67c64dfb2a84/lib/presentation_layer/view_models/post_page_view_model.dart#L7-L19

について

ViewからViewModelにWidgetRef渡していますが、渡さなくても実装できるはずです！
`PostPageViewModel` のインスタンス化を Riverpod を使ってやってみてください！

**Comment by nozomi-koborinai** [comment]
多くのご指摘ありがとうございます！😊
修正してみました。

**`レイヤーを意識しましょう`**  について、
> 全てのプロバイダをドメイン層のファイルに持たせる必要もないと考えて、そのプロバイダ達を役割ごとに
> `infrastructure_providers`, 
`presentation_providers`のファイルに分割してみました。

**`リポジトリ（実体）が受け取るコンストラクタ`** について、

> 今までFirebaseFirestoreのインスタンスを受取るようにしていましいたが、CollectionReferenceを受け取るようにしました。
> こちらの方が、コードがスッキリして見えます！

**`ViewModelの生成にもRiverpodが使えます`** について、

> ViewModelに初期化処理としてviewからWidgetRefを渡してもらうようにしていましたが、ViewModelのコンストラクタに`ProviderRef`を追加して、プロバイダ内でViewModelをインスタンス化する際にrefを渡すようにしてみました。

**Comment by susatthi** [comment]
b1415c02af7edebc48c172f7f58196a5f025389f
を追加レビューしました！

## 全体

- レイヤー分け、Riverpodの使い方、だいぶよくなったと思います！

## レビュー

https://github.com/nzmgfdprs/repository_riverpod_mvvm/blob/b1415c02af7edebc48c172f7f58196a5f025389f/lib/infrastructure_layer/repositories/post_repository.dart#L15-L16

freezed の機能にある `newPost.toJson()` が使えそうです。試してみて下さい！

https://github.com/nzmgfdprs/repository_riverpod_mvvm/blob/b1415c02af7edebc48c172f7f58196a5f025389f/lib/infrastructure_layer/infrastructure_providers.dart#L8-L11

ドメイン層の Interface に対するプロバイダーなのでドメイン層で定義した方が自然だと思います！

https://github.com/nzmgfdprs/repository_riverpod_mvvm/blob/b1415c02af7edebc48c172f7f58196a5f025389f/lib/presentation_layer/view_models/post_page_view_model.dart#L16-L22

`ref.watch` にしてますが、`ref.read` としたほうが自然です。

`ref.watch`とすることで、プロバイダーの再生成が伝搬してくれますが、事前に実行しておかないといけません。Widget の build() 内で watch をするとリビルドしてくれるのは、事前に実行しているためです。

例えば、呼ばれないルートも存在するので `pageTitle` がgetされて、`ref.watch(postTitleProvider)` が確実に実行されるとはいいきれないと思います。なので、`postTitleProvider`が再生成されても、pageTitleが更新されるとは言い切れないので、`ref.read`としておいた方が良いと思います（私も実験していないと確実なことは言えないのですが。。）。

https://github.com/nzmgfdprs/repository_riverpod_mvvm/blob/b1415c02af7edebc48c172f7f58196a5f025389f/lib/presentation_layer/presentation_providers.dart#L7-L9

個人的な意見なので、一意見として聞いてほしいのですが、私だったら上記Providerは、`PostPageViewModel` を定義しているファイルに書きます。関連しているコードが1箇所にまとまっていたほうがコードが読みやすいと思うからです。

**Comment by susatthi** [comment]
レイヤー分けという観点からのレビューは今回でおしまいです！かなりよくなったと思います。
細かいところを指摘しようとすればできますが、まずは自分なりに試して改善していったほうがよいと思うのであえて止めておきます！

## レビュー

https://github.com/nzmgfdprs/repository_riverpod_mvvm/commit/72968d676019ba91905de1d67c2cbfb3c89d40bf

ごめんなさい。`toJson()` じゃないほうが良いと思い直しました。。。ドメイン層はどこにも依存しないので、ドメイン層のエンティティを何かに変換する際、変換後の形式（今回はJSON形式）を意識しないほうがよいと思い直しました。でも、`toJson()`を絶対使ってはいけないとも思わないので、好みの範疇とも思います。お任せします！
